theme: jekyll-theme-modernist


title: Juan Luis Mora
description: Lider, Comunicador, Coherente, Cercano, Profesional.
show_downloads: false
github:
  is_user_page: false
  repository_url: https://twitter.com/jmoras07
  is_project_page: false
  github_name: jmoras07
  
footballcloud:
  url: https://footballcloud.net
  editor: pedrogarcia
  
#  ![Octocat](https://pbs.twimg.com/profile_images/1034213562753994754/7M9-xAUG_400x400.jpg)
#![Branching](https://pbs.twimg.com/media/DkivQp-XcAAQJsq.jpg)